server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postsDB
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true